// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserSubscriptionCreate is the builder for creating a UserSubscription entity.
type UserSubscriptionCreate struct {
	config
	mutation *UserSubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSubscriptionCreate) SetCreatedAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSubscriptionCreate) SetUpdatedAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserSubscriptionCreate) SetDeletedAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableDeletedAt(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserSubscriptionCreate) SetUserID(v int64) *UserSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserSubscriptionCreate) SetGroupID(v int64) *UserSubscriptionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserSubscriptionCreate) SetStartsAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserSubscriptionCreate) SetExpiresAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserSubscriptionCreate) SetStatus(v string) *UserSubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStatus(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_c *UserSubscriptionCreate) SetStripeCustomerID(v string) *UserSubscriptionCreate {
	_c.mutation.SetStripeCustomerID(v)
	return _c
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStripeCustomerID(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStripeCustomerID(*v)
	}
	return _c
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_c *UserSubscriptionCreate) SetStripeSubscriptionID(v string) *UserSubscriptionCreate {
	_c.mutation.SetStripeSubscriptionID(v)
	return _c
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStripeSubscriptionID(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStripeSubscriptionID(*v)
	}
	return _c
}

// SetStripePriceID sets the "stripe_price_id" field.
func (_c *UserSubscriptionCreate) SetStripePriceID(v string) *UserSubscriptionCreate {
	_c.mutation.SetStripePriceID(v)
	return _c
}

// SetNillableStripePriceID sets the "stripe_price_id" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStripePriceID(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStripePriceID(*v)
	}
	return _c
}

// SetStripeEnvironment sets the "stripe_environment" field.
func (_c *UserSubscriptionCreate) SetStripeEnvironment(v string) *UserSubscriptionCreate {
	_c.mutation.SetStripeEnvironment(v)
	return _c
}

// SetNillableStripeEnvironment sets the "stripe_environment" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStripeEnvironment(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStripeEnvironment(*v)
	}
	return _c
}

// SetStripeProviderInstanceID sets the "stripe_provider_instance_id" field.
func (_c *UserSubscriptionCreate) SetStripeProviderInstanceID(v string) *UserSubscriptionCreate {
	_c.mutation.SetStripeProviderInstanceID(v)
	return _c
}

// SetNillableStripeProviderInstanceID sets the "stripe_provider_instance_id" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStripeProviderInstanceID(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStripeProviderInstanceID(*v)
	}
	return _c
}

// SetStripeStatus sets the "stripe_status" field.
func (_c *UserSubscriptionCreate) SetStripeStatus(v string) *UserSubscriptionCreate {
	_c.mutation.SetStripeStatus(v)
	return _c
}

// SetNillableStripeStatus sets the "stripe_status" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableStripeStatus(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetStripeStatus(*v)
	}
	return _c
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_c *UserSubscriptionCreate) SetCurrentPeriodStart(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetCurrentPeriodStart(v)
	return _c
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableCurrentPeriodStart(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetCurrentPeriodStart(*v)
	}
	return _c
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_c *UserSubscriptionCreate) SetCurrentPeriodEnd(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetCurrentPeriodEnd(v)
	return _c
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableCurrentPeriodEnd(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetCurrentPeriodEnd(*v)
	}
	return _c
}

// SetTrialStart sets the "trial_start" field.
func (_c *UserSubscriptionCreate) SetTrialStart(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetTrialStart(v)
	return _c
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableTrialStart(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetTrialStart(*v)
	}
	return _c
}

// SetTrialEnd sets the "trial_end" field.
func (_c *UserSubscriptionCreate) SetTrialEnd(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetTrialEnd(v)
	return _c
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableTrialEnd(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetTrialEnd(*v)
	}
	return _c
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_c *UserSubscriptionCreate) SetCancelAtPeriodEnd(v bool) *UserSubscriptionCreate {
	_c.mutation.SetCancelAtPeriodEnd(v)
	return _c
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableCancelAtPeriodEnd(v *bool) *UserSubscriptionCreate {
	if v != nil {
		_c.SetCancelAtPeriodEnd(*v)
	}
	return _c
}

// SetPastDueSince sets the "past_due_since" field.
func (_c *UserSubscriptionCreate) SetPastDueSince(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetPastDueSince(v)
	return _c
}

// SetNillablePastDueSince sets the "past_due_since" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillablePastDueSince(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetPastDueSince(*v)
	}
	return _c
}

// SetTrialUsed sets the "trial_used" field.
func (_c *UserSubscriptionCreate) SetTrialUsed(v bool) *UserSubscriptionCreate {
	_c.mutation.SetTrialUsed(v)
	return _c
}

// SetNillableTrialUsed sets the "trial_used" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableTrialUsed(v *bool) *UserSubscriptionCreate {
	if v != nil {
		_c.SetTrialUsed(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *UserSubscriptionCreate) SetDailyWindowStart(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableDailyWindowStart(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *UserSubscriptionCreate) SetWeeklyWindowStart(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableWeeklyWindowStart(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *UserSubscriptionCreate) SetMonthlyWindowStart(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableMonthlyWindowStart(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *UserSubscriptionCreate) SetDailyUsageUsd(v float64) *UserSubscriptionCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableDailyUsageUsd(v *float64) *UserSubscriptionCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *UserSubscriptionCreate) SetWeeklyUsageUsd(v float64) *UserSubscriptionCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableWeeklyUsageUsd(v *float64) *UserSubscriptionCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *UserSubscriptionCreate) SetMonthlyUsageUsd(v float64) *UserSubscriptionCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableMonthlyUsageUsd(v *float64) *UserSubscriptionCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *UserSubscriptionCreate) SetAssignedBy(v int64) *UserSubscriptionCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableAssignedBy(v *int64) *UserSubscriptionCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *UserSubscriptionCreate) SetAssignedAt(v time.Time) *UserSubscriptionCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableAssignedAt(v *time.Time) *UserSubscriptionCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserSubscriptionCreate) SetNotes(v string) *UserSubscriptionCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableNotes(v *string) *UserSubscriptionCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserSubscriptionCreate) SetUser(v *User) *UserSubscriptionCreate {
	return _c.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *UserSubscriptionCreate) SetGroup(v *Group) *UserSubscriptionCreate {
	return _c.SetGroupID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_c *UserSubscriptionCreate) SetAssignedByUserID(id int64) *UserSubscriptionCreate {
	_c.mutation.SetAssignedByUserID(id)
	return _c
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *UserSubscriptionCreate) SetNillableAssignedByUserID(id *int64) *UserSubscriptionCreate {
	if id != nil {
		_c = _c.SetAssignedByUserID(*id)
	}
	return _c
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_c *UserSubscriptionCreate) SetAssignedByUser(v *User) *UserSubscriptionCreate {
	return _c.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *UserSubscriptionCreate) AddUsageLogIDs(ids ...int64) *UserSubscriptionCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *UserSubscriptionCreate) AddUsageLogs(v ...*UsageLog) *UserSubscriptionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (_c *UserSubscriptionCreate) Mutation() *UserSubscriptionMutation {
	return _c.mutation
}

// Save creates the UserSubscription in the database.
func (_c *UserSubscriptionCreate) Save(ctx context.Context) (*UserSubscription, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSubscriptionCreate) SaveX(ctx context.Context) *UserSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSubscriptionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usersubscription.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usersubscription.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usersubscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StripeEnvironment(); !ok {
		v := usersubscription.DefaultStripeEnvironment
		_c.mutation.SetStripeEnvironment(v)
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		v := usersubscription.DefaultCancelAtPeriodEnd
		_c.mutation.SetCancelAtPeriodEnd(v)
	}
	if _, ok := _c.mutation.TrialUsed(); !ok {
		v := usersubscription.DefaultTrialUsed
		_c.mutation.SetTrialUsed(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := usersubscription.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := usersubscription.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := usersubscription.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		if usersubscription.DefaultAssignedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.DefaultAssignedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSubscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSubscription.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserSubscription.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserSubscription.group_id"`)}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserSubscription.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserSubscription.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserSubscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usersubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripeCustomerID(); ok {
		if err := usersubscription.StripeCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_customer_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_customer_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripeSubscriptionID(); ok {
		if err := usersubscription.StripeSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_subscription_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_subscription_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripePriceID(); ok {
		if err := usersubscription.StripePriceIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_price_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_price_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StripeEnvironment(); !ok {
		return &ValidationError{Name: "stripe_environment", err: errors.New(`ent: missing required field "UserSubscription.stripe_environment"`)}
	}
	if v, ok := _c.mutation.StripeEnvironment(); ok {
		if err := usersubscription.StripeEnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "stripe_environment", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_environment": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripeProviderInstanceID(); ok {
		if err := usersubscription.StripeProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripeStatus(); ok {
		if err := usersubscription.StripeStatusValidator(v); err != nil {
			return &ValidationError{Name: "stripe_status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		return &ValidationError{Name: "cancel_at_period_end", err: errors.New(`ent: missing required field "UserSubscription.cancel_at_period_end"`)}
	}
	if _, ok := _c.mutation.TrialUsed(); !ok {
		return &ValidationError{Name: "trial_used", err: errors.New(`ent: missing required field "UserSubscription.trial_used"`)}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "UserSubscription.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "UserSubscription.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "UserSubscription.monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "UserSubscription.assigned_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserSubscription.user"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "UserSubscription.group"`)}
	}
	return nil
}

func (_c *UserSubscriptionCreate) sqlSave(ctx context.Context) (*UserSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSubscriptionCreate) createSpec() (*UserSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersubscription.Table, sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(usersubscription.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(usersubscription.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscription.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usersubscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StripeCustomerID(); ok {
		_spec.SetField(usersubscription.FieldStripeCustomerID, field.TypeString, value)
		_node.StripeCustomerID = &value
	}
	if value, ok := _c.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(usersubscription.FieldStripeSubscriptionID, field.TypeString, value)
		_node.StripeSubscriptionID = &value
	}
	if value, ok := _c.mutation.StripePriceID(); ok {
		_spec.SetField(usersubscription.FieldStripePriceID, field.TypeString, value)
		_node.StripePriceID = &value
	}
	if value, ok := _c.mutation.StripeEnvironment(); ok {
		_spec.SetField(usersubscription.FieldStripeEnvironment, field.TypeString, value)
		_node.StripeEnvironment = value
	}
	if value, ok := _c.mutation.StripeProviderInstanceID(); ok {
		_spec.SetField(usersubscription.FieldStripeProviderInstanceID, field.TypeString, value)
		_node.StripeProviderInstanceID = &value
	}
	if value, ok := _c.mutation.StripeStatus(); ok {
		_spec.SetField(usersubscription.FieldStripeStatus, field.TypeString, value)
		_node.StripeStatus = &value
	}
	if value, ok := _c.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(usersubscription.FieldCurrentPeriodStart, field.TypeTime, value)
		_node.CurrentPeriodStart = &value
	}
	if value, ok := _c.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(usersubscription.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = &value
	}
	if value, ok := _c.mutation.TrialStart(); ok {
		_spec.SetField(usersubscription.FieldTrialStart, field.TypeTime, value)
		_node.TrialStart = &value
	}
	if value, ok := _c.mutation.TrialEnd(); ok {
		_spec.SetField(usersubscription.FieldTrialEnd, field.TypeTime, value)
		_node.TrialEnd = &value
	}
	if value, ok := _c.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(usersubscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
		_node.CancelAtPeriodEnd = value
	}
	if value, ok := _c.mutation.PastDueSince(); ok {
		_spec.SetField(usersubscription.FieldPastDueSince, field.TypeTime, value)
		_node.PastDueSince = &value
	}
	if value, ok := _c.mutation.TrialUsed(); ok {
		_spec.SetField(usersubscription.FieldTrialUsed, field.TypeBool, value)
		_node.TrialUsed = value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(usersubscription.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(usersubscription.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.UserTable,
			Columns: []string{usersubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.GroupTable,
			Columns: []string{usersubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.AssignedByUserTable,
			Columns: []string{usersubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssignedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionUpsertOne {
	_c.conflict = opts
	return &UserSubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionCreate) OnConflictColumns(columns ...string) *UserSubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// UserSubscriptionUpsertOne is the builder for "upsert"-ing
	//  one UserSubscription node.
	UserSubscriptionUpsertOne struct {
		create *UserSubscriptionCreate
	}

	// UserSubscriptionUpsert is the "OnConflict" setter.
	UserSubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionUpsert) SetUpdatedAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateUpdatedAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserSubscriptionUpsert) SetDeletedAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateDeletedAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserSubscriptionUpsert) ClearDeletedAt() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserSubscriptionUpsert) SetUserID(v int64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateUserID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserSubscriptionUpsert) SetGroupID(v int64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateGroupID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldGroupID)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionUpsert) SetStartsAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStartsAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionUpsert) SetExpiresAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateExpiresAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionUpsert) SetStatus(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStatus() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStatus)
	return u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (u *UserSubscriptionUpsert) SetStripeCustomerID(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStripeCustomerID, v)
	return u
}

// UpdateStripeCustomerID sets the "stripe_customer_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStripeCustomerID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStripeCustomerID)
	return u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (u *UserSubscriptionUpsert) ClearStripeCustomerID() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldStripeCustomerID)
	return u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (u *UserSubscriptionUpsert) SetStripeSubscriptionID(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStripeSubscriptionID, v)
	return u
}

// UpdateStripeSubscriptionID sets the "stripe_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStripeSubscriptionID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStripeSubscriptionID)
	return u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (u *UserSubscriptionUpsert) ClearStripeSubscriptionID() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldStripeSubscriptionID)
	return u
}

// SetStripePriceID sets the "stripe_price_id" field.
func (u *UserSubscriptionUpsert) SetStripePriceID(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStripePriceID, v)
	return u
}

// UpdateStripePriceID sets the "stripe_price_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStripePriceID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStripePriceID)
	return u
}

// ClearStripePriceID clears the value of the "stripe_price_id" field.
func (u *UserSubscriptionUpsert) ClearStripePriceID() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldStripePriceID)
	return u
}

// SetStripeEnvironment sets the "stripe_environment" field.
func (u *UserSubscriptionUpsert) SetStripeEnvironment(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStripeEnvironment, v)
	return u
}

// UpdateStripeEnvironment sets the "stripe_environment" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStripeEnvironment() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStripeEnvironment)
	return u
}

// SetStripeProviderInstanceID sets the "stripe_provider_instance_id" field.
func (u *UserSubscriptionUpsert) SetStripeProviderInstanceID(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStripeProviderInstanceID, v)
	return u
}

// UpdateStripeProviderInstanceID sets the "stripe_provider_instance_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStripeProviderInstanceID() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStripeProviderInstanceID)
	return u
}

// ClearStripeProviderInstanceID clears the value of the "stripe_provider_instance_id" field.
func (u *UserSubscriptionUpsert) ClearStripeProviderInstanceID() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldStripeProviderInstanceID)
	return u
}

// SetStripeStatus sets the "stripe_status" field.
func (u *UserSubscriptionUpsert) SetStripeStatus(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldStripeStatus, v)
	return u
}

// UpdateStripeStatus sets the "stripe_status" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateStripeStatus() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldStripeStatus)
	return u
}

// ClearStripeStatus clears the value of the "stripe_status" field.
func (u *UserSubscriptionUpsert) ClearStripeStatus() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldStripeStatus)
	return u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *UserSubscriptionUpsert) SetCurrentPeriodStart(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldCurrentPeriodStart, v)
	return u
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateCurrentPeriodStart() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldCurrentPeriodStart)
	return u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (u *UserSubscriptionUpsert) ClearCurrentPeriodStart() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldCurrentPeriodStart)
	return u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *UserSubscriptionUpsert) SetCurrentPeriodEnd(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldCurrentPeriodEnd, v)
	return u
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateCurrentPeriodEnd() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldCurrentPeriodEnd)
	return u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (u *UserSubscriptionUpsert) ClearCurrentPeriodEnd() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldCurrentPeriodEnd)
	return u
}

// SetTrialStart sets the "trial_start" field.
func (u *UserSubscriptionUpsert) SetTrialStart(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldTrialStart, v)
	return u
}

// UpdateTrialStart sets the "trial_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateTrialStart() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldTrialStart)
	return u
}

// ClearTrialStart clears the value of the "trial_start" field.
func (u *UserSubscriptionUpsert) ClearTrialStart() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldTrialStart)
	return u
}

// SetTrialEnd sets the "trial_end" field.
func (u *UserSubscriptionUpsert) SetTrialEnd(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldTrialEnd, v)
	return u
}

// UpdateTrialEnd sets the "trial_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateTrialEnd() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldTrialEnd)
	return u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (u *UserSubscriptionUpsert) ClearTrialEnd() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldTrialEnd)
	return u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *UserSubscriptionUpsert) SetCancelAtPeriodEnd(v bool) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldCancelAtPeriodEnd, v)
	return u
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateCancelAtPeriodEnd() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldCancelAtPeriodEnd)
	return u
}

// SetPastDueSince sets the "past_due_since" field.
func (u *UserSubscriptionUpsert) SetPastDueSince(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldPastDueSince, v)
	return u
}

// UpdatePastDueSince sets the "past_due_since" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdatePastDueSince() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldPastDueSince)
	return u
}

// ClearPastDueSince clears the value of the "past_due_since" field.
func (u *UserSubscriptionUpsert) ClearPastDueSince() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldPastDueSince)
	return u
}

// SetTrialUsed sets the "trial_used" field.
func (u *UserSubscriptionUpsert) SetTrialUsed(v bool) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldTrialUsed, v)
	return u
}

// UpdateTrialUsed sets the "trial_used" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateTrialUsed() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldTrialUsed)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserSubscriptionUpsert) SetDailyWindowStart(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateDailyWindowStart() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserSubscriptionUpsert) ClearDailyWindowStart() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserSubscriptionUpsert) SetWeeklyWindowStart(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateWeeklyWindowStart() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserSubscriptionUpsert) ClearWeeklyWindowStart() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserSubscriptionUpsert) SetMonthlyWindowStart(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateMonthlyWindowStart() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserSubscriptionUpsert) ClearMonthlyWindowStart() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldMonthlyWindowStart)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserSubscriptionUpsert) SetDailyUsageUsd(v float64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateDailyUsageUsd() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserSubscriptionUpsert) AddDailyUsageUsd(v float64) *UserSubscriptionUpsert {
	u.Add(usersubscription.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserSubscriptionUpsert) SetWeeklyUsageUsd(v float64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateWeeklyUsageUsd() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserSubscriptionUpsert) AddWeeklyUsageUsd(v float64) *UserSubscriptionUpsert {
	u.Add(usersubscription.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserSubscriptionUpsert) SetMonthlyUsageUsd(v float64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateMonthlyUsageUsd() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserSubscriptionUpsert) AddMonthlyUsageUsd(v float64) *UserSubscriptionUpsert {
	u.Add(usersubscription.FieldMonthlyUsageUsd, v)
	return u
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserSubscriptionUpsert) SetAssignedBy(v int64) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldAssignedBy, v)
	return u
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateAssignedBy() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldAssignedBy)
	return u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserSubscriptionUpsert) ClearAssignedBy() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldAssignedBy)
	return u
}

// SetAssignedAt sets the "assigned_at" field.
func (u *UserSubscriptionUpsert) SetAssignedAt(v time.Time) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldAssignedAt, v)
	return u
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateAssignedAt() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldAssignedAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserSubscriptionUpsert) SetNotes(v string) *UserSubscriptionUpsert {
	u.Set(usersubscription.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserSubscriptionUpsert) UpdateNotes() *UserSubscriptionUpsert {
	u.SetExcluded(usersubscription.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *UserSubscriptionUpsert) ClearNotes() *UserSubscriptionUpsert {
	u.SetNull(usersubscription.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionUpsertOne) UpdateNewValues() *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usersubscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserSubscriptionUpsertOne) Ignore() *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionUpsertOne) DoNothing() *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionCreate.OnConflict
// documentation for more info.
func (u *UserSubscriptionUpsertOne) Update(set func(*UserSubscriptionUpsert)) *UserSubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionUpsertOne) SetUpdatedAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateUpdatedAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserSubscriptionUpsertOne) SetDeletedAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateDeletedAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserSubscriptionUpsertOne) ClearDeletedAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserSubscriptionUpsertOne) SetUserID(v int64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateUserID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserSubscriptionUpsertOne) SetGroupID(v int64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateGroupID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateGroupID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionUpsertOne) SetStartsAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStartsAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionUpsertOne) SetExpiresAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateExpiresAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionUpsertOne) SetStatus(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStatus() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (u *UserSubscriptionUpsertOne) SetStripeCustomerID(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeCustomerID(v)
	})
}

// UpdateStripeCustomerID sets the "stripe_customer_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStripeCustomerID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeCustomerID()
	})
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (u *UserSubscriptionUpsertOne) ClearStripeCustomerID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeCustomerID()
	})
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (u *UserSubscriptionUpsertOne) SetStripeSubscriptionID(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeSubscriptionID(v)
	})
}

// UpdateStripeSubscriptionID sets the "stripe_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStripeSubscriptionID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeSubscriptionID()
	})
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (u *UserSubscriptionUpsertOne) ClearStripeSubscriptionID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeSubscriptionID()
	})
}

// SetStripePriceID sets the "stripe_price_id" field.
func (u *UserSubscriptionUpsertOne) SetStripePriceID(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripePriceID(v)
	})
}

// UpdateStripePriceID sets the "stripe_price_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStripePriceID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripePriceID()
	})
}

// ClearStripePriceID clears the value of the "stripe_price_id" field.
func (u *UserSubscriptionUpsertOne) ClearStripePriceID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripePriceID()
	})
}

// SetStripeEnvironment sets the "stripe_environment" field.
func (u *UserSubscriptionUpsertOne) SetStripeEnvironment(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeEnvironment(v)
	})
}

// UpdateStripeEnvironment sets the "stripe_environment" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStripeEnvironment() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeEnvironment()
	})
}

// SetStripeProviderInstanceID sets the "stripe_provider_instance_id" field.
func (u *UserSubscriptionUpsertOne) SetStripeProviderInstanceID(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeProviderInstanceID(v)
	})
}

// UpdateStripeProviderInstanceID sets the "stripe_provider_instance_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStripeProviderInstanceID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeProviderInstanceID()
	})
}

// ClearStripeProviderInstanceID clears the value of the "stripe_provider_instance_id" field.
func (u *UserSubscriptionUpsertOne) ClearStripeProviderInstanceID() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeProviderInstanceID()
	})
}

// SetStripeStatus sets the "stripe_status" field.
func (u *UserSubscriptionUpsertOne) SetStripeStatus(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeStatus(v)
	})
}

// UpdateStripeStatus sets the "stripe_status" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateStripeStatus() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeStatus()
	})
}

// ClearStripeStatus clears the value of the "stripe_status" field.
func (u *UserSubscriptionUpsertOne) ClearStripeStatus() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeStatus()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *UserSubscriptionUpsertOne) SetCurrentPeriodStart(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateCurrentPeriodStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (u *UserSubscriptionUpsertOne) ClearCurrentPeriodStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearCurrentPeriodStart()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *UserSubscriptionUpsertOne) SetCurrentPeriodEnd(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateCurrentPeriodEnd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (u *UserSubscriptionUpsertOne) ClearCurrentPeriodEnd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearCurrentPeriodEnd()
	})
}

// SetTrialStart sets the "trial_start" field.
func (u *UserSubscriptionUpsertOne) SetTrialStart(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetTrialStart(v)
	})
}

// UpdateTrialStart sets the "trial_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateTrialStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateTrialStart()
	})
}

// ClearTrialStart clears the value of the "trial_start" field.
func (u *UserSubscriptionUpsertOne) ClearTrialStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearTrialStart()
	})
}

// SetTrialEnd sets the "trial_end" field.
func (u *UserSubscriptionUpsertOne) SetTrialEnd(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetTrialEnd(v)
	})
}

// UpdateTrialEnd sets the "trial_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateTrialEnd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateTrialEnd()
	})
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (u *UserSubscriptionUpsertOne) ClearTrialEnd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearTrialEnd()
	})
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *UserSubscriptionUpsertOne) SetCancelAtPeriodEnd(v bool) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetCancelAtPeriodEnd(v)
	})
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateCancelAtPeriodEnd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateCancelAtPeriodEnd()
	})
}

// SetPastDueSince sets the "past_due_since" field.
func (u *UserSubscriptionUpsertOne) SetPastDueSince(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetPastDueSince(v)
	})
}

// UpdatePastDueSince sets the "past_due_since" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdatePastDueSince() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdatePastDueSince()
	})
}

// ClearPastDueSince clears the value of the "past_due_since" field.
func (u *UserSubscriptionUpsertOne) ClearPastDueSince() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearPastDueSince()
	})
}

// SetTrialUsed sets the "trial_used" field.
func (u *UserSubscriptionUpsertOne) SetTrialUsed(v bool) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetTrialUsed(v)
	})
}

// UpdateTrialUsed sets the "trial_used" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateTrialUsed() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateTrialUsed()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserSubscriptionUpsertOne) SetDailyWindowStart(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateDailyWindowStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserSubscriptionUpsertOne) ClearDailyWindowStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserSubscriptionUpsertOne) SetWeeklyWindowStart(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateWeeklyWindowStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserSubscriptionUpsertOne) ClearWeeklyWindowStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserSubscriptionUpsertOne) SetMonthlyWindowStart(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateMonthlyWindowStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserSubscriptionUpsertOne) ClearMonthlyWindowStart() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserSubscriptionUpsertOne) SetDailyUsageUsd(v float64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserSubscriptionUpsertOne) AddDailyUsageUsd(v float64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateDailyUsageUsd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserSubscriptionUpsertOne) SetWeeklyUsageUsd(v float64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserSubscriptionUpsertOne) AddWeeklyUsageUsd(v float64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateWeeklyUsageUsd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserSubscriptionUpsertOne) SetMonthlyUsageUsd(v float64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserSubscriptionUpsertOne) AddMonthlyUsageUsd(v float64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateMonthlyUsageUsd() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserSubscriptionUpsertOne) SetAssignedBy(v int64) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateAssignedBy() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserSubscriptionUpsertOne) ClearAssignedBy() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *UserSubscriptionUpsertOne) SetAssignedAt(v time.Time) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateAssignedAt() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *UserSubscriptionUpsertOne) SetNotes(v string) *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserSubscriptionUpsertOne) UpdateNotes() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserSubscriptionUpsertOne) ClearNotes() *UserSubscriptionUpsertOne {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *UserSubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserSubscriptionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserSubscriptionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserSubscriptionCreateBulk is the builder for creating many UserSubscription entities in bulk.
type UserSubscriptionCreateBulk struct {
	config
	err      error
	builders []*UserSubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the UserSubscription entities in the database.
func (_c *UserSubscriptionCreateBulk) Save(ctx context.Context) ([]*UserSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSubscriptionCreateBulk) SaveX(ctx context.Context) []*UserSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionUpsertBulk {
	_c.conflict = opts
	return &UserSubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionCreateBulk) OnConflictColumns(columns ...string) *UserSubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionUpsertBulk{
		create: _c,
	}
}

// UserSubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of UserSubscription nodes.
type UserSubscriptionUpsertBulk struct {
	create *UserSubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionUpsertBulk) UpdateNewValues() *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usersubscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserSubscriptionUpsertBulk) Ignore() *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionUpsertBulk) DoNothing() *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *UserSubscriptionUpsertBulk) Update(set func(*UserSubscriptionUpsert)) *UserSubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateUpdatedAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserSubscriptionUpsertBulk) SetDeletedAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateDeletedAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserSubscriptionUpsertBulk) ClearDeletedAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserSubscriptionUpsertBulk) SetUserID(v int64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateUserID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserSubscriptionUpsertBulk) SetGroupID(v int64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateGroupID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateGroupID()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionUpsertBulk) SetStartsAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStartsAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionUpsertBulk) SetExpiresAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateExpiresAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionUpsertBulk) SetStatus(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStatus() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (u *UserSubscriptionUpsertBulk) SetStripeCustomerID(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeCustomerID(v)
	})
}

// UpdateStripeCustomerID sets the "stripe_customer_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStripeCustomerID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeCustomerID()
	})
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (u *UserSubscriptionUpsertBulk) ClearStripeCustomerID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeCustomerID()
	})
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (u *UserSubscriptionUpsertBulk) SetStripeSubscriptionID(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeSubscriptionID(v)
	})
}

// UpdateStripeSubscriptionID sets the "stripe_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStripeSubscriptionID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeSubscriptionID()
	})
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (u *UserSubscriptionUpsertBulk) ClearStripeSubscriptionID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeSubscriptionID()
	})
}

// SetStripePriceID sets the "stripe_price_id" field.
func (u *UserSubscriptionUpsertBulk) SetStripePriceID(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripePriceID(v)
	})
}

// UpdateStripePriceID sets the "stripe_price_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStripePriceID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripePriceID()
	})
}

// ClearStripePriceID clears the value of the "stripe_price_id" field.
func (u *UserSubscriptionUpsertBulk) ClearStripePriceID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripePriceID()
	})
}

// SetStripeEnvironment sets the "stripe_environment" field.
func (u *UserSubscriptionUpsertBulk) SetStripeEnvironment(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeEnvironment(v)
	})
}

// UpdateStripeEnvironment sets the "stripe_environment" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStripeEnvironment() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeEnvironment()
	})
}

// SetStripeProviderInstanceID sets the "stripe_provider_instance_id" field.
func (u *UserSubscriptionUpsertBulk) SetStripeProviderInstanceID(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeProviderInstanceID(v)
	})
}

// UpdateStripeProviderInstanceID sets the "stripe_provider_instance_id" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStripeProviderInstanceID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeProviderInstanceID()
	})
}

// ClearStripeProviderInstanceID clears the value of the "stripe_provider_instance_id" field.
func (u *UserSubscriptionUpsertBulk) ClearStripeProviderInstanceID() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeProviderInstanceID()
	})
}

// SetStripeStatus sets the "stripe_status" field.
func (u *UserSubscriptionUpsertBulk) SetStripeStatus(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetStripeStatus(v)
	})
}

// UpdateStripeStatus sets the "stripe_status" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateStripeStatus() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateStripeStatus()
	})
}

// ClearStripeStatus clears the value of the "stripe_status" field.
func (u *UserSubscriptionUpsertBulk) ClearStripeStatus() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearStripeStatus()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *UserSubscriptionUpsertBulk) SetCurrentPeriodStart(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateCurrentPeriodStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (u *UserSubscriptionUpsertBulk) ClearCurrentPeriodStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearCurrentPeriodStart()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *UserSubscriptionUpsertBulk) SetCurrentPeriodEnd(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateCurrentPeriodEnd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (u *UserSubscriptionUpsertBulk) ClearCurrentPeriodEnd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearCurrentPeriodEnd()
	})
}

// SetTrialStart sets the "trial_start" field.
func (u *UserSubscriptionUpsertBulk) SetTrialStart(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetTrialStart(v)
	})
}

// UpdateTrialStart sets the "trial_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateTrialStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateTrialStart()
	})
}

// ClearTrialStart clears the value of the "trial_start" field.
func (u *UserSubscriptionUpsertBulk) ClearTrialStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearTrialStart()
	})
}

// SetTrialEnd sets the "trial_end" field.
func (u *UserSubscriptionUpsertBulk) SetTrialEnd(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetTrialEnd(v)
	})
}

// UpdateTrialEnd sets the "trial_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateTrialEnd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateTrialEnd()
	})
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (u *UserSubscriptionUpsertBulk) ClearTrialEnd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearTrialEnd()
	})
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *UserSubscriptionUpsertBulk) SetCancelAtPeriodEnd(v bool) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetCancelAtPeriodEnd(v)
	})
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateCancelAtPeriodEnd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateCancelAtPeriodEnd()
	})
}

// SetPastDueSince sets the "past_due_since" field.
func (u *UserSubscriptionUpsertBulk) SetPastDueSince(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetPastDueSince(v)
	})
}

// UpdatePastDueSince sets the "past_due_since" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdatePastDueSince() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdatePastDueSince()
	})
}

// ClearPastDueSince clears the value of the "past_due_since" field.
func (u *UserSubscriptionUpsertBulk) ClearPastDueSince() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearPastDueSince()
	})
}

// SetTrialUsed sets the "trial_used" field.
func (u *UserSubscriptionUpsertBulk) SetTrialUsed(v bool) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetTrialUsed(v)
	})
}

// UpdateTrialUsed sets the "trial_used" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateTrialUsed() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateTrialUsed()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserSubscriptionUpsertBulk) SetDailyWindowStart(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateDailyWindowStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserSubscriptionUpsertBulk) ClearDailyWindowStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserSubscriptionUpsertBulk) SetWeeklyWindowStart(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateWeeklyWindowStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserSubscriptionUpsertBulk) ClearWeeklyWindowStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserSubscriptionUpsertBulk) SetMonthlyWindowStart(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateMonthlyWindowStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserSubscriptionUpsertBulk) ClearMonthlyWindowStart() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserSubscriptionUpsertBulk) SetDailyUsageUsd(v float64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserSubscriptionUpsertBulk) AddDailyUsageUsd(v float64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateDailyUsageUsd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserSubscriptionUpsertBulk) SetWeeklyUsageUsd(v float64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserSubscriptionUpsertBulk) AddWeeklyUsageUsd(v float64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateWeeklyUsageUsd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserSubscriptionUpsertBulk) SetMonthlyUsageUsd(v float64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserSubscriptionUpsertBulk) AddMonthlyUsageUsd(v float64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateMonthlyUsageUsd() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetAssignedBy sets the "assigned_by" field.
func (u *UserSubscriptionUpsertBulk) SetAssignedBy(v int64) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetAssignedBy(v)
	})
}

// UpdateAssignedBy sets the "assigned_by" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateAssignedBy() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateAssignedBy()
	})
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (u *UserSubscriptionUpsertBulk) ClearAssignedBy() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearAssignedBy()
	})
}

// SetAssignedAt sets the "assigned_at" field.
func (u *UserSubscriptionUpsertBulk) SetAssignedAt(v time.Time) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetAssignedAt(v)
	})
}

// UpdateAssignedAt sets the "assigned_at" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateAssignedAt() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateAssignedAt()
	})
}

// SetNotes sets the "notes" field.
func (u *UserSubscriptionUpsertBulk) SetNotes(v string) *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserSubscriptionUpsertBulk) UpdateNotes() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *UserSubscriptionUpsertBulk) ClearNotes() *UserSubscriptionUpsertBulk {
	return u.Update(func(s *UserSubscriptionUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *UserSubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserSubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
