// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserSubscriptionUpdate is the builder for updating UserSubscription entities.
type UserSubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *UserSubscriptionMutation
}

// Where appends a list predicates to the UserSubscriptionUpdate builder.
func (_u *UserSubscriptionUpdate) Where(ps ...predicate.UserSubscription) *UserSubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscriptionUpdate) SetUpdatedAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserSubscriptionUpdate) SetDeletedAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableDeletedAt(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserSubscriptionUpdate) ClearDeletedAt() *UserSubscriptionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSubscriptionUpdate) SetUserID(v int64) *UserSubscriptionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableUserID(v *int64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserSubscriptionUpdate) SetGroupID(v int64) *UserSubscriptionUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableGroupID(v *int64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserSubscriptionUpdate) SetStartsAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStartsAt(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserSubscriptionUpdate) SetExpiresAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableExpiresAt(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscriptionUpdate) SetStatus(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStatus(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *UserSubscriptionUpdate) SetStripeCustomerID(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStripeCustomerID(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *UserSubscriptionUpdate) ClearStripeCustomerID() *UserSubscriptionUpdate {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *UserSubscriptionUpdate) SetStripeSubscriptionID(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStripeSubscriptionID(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *UserSubscriptionUpdate) ClearStripeSubscriptionID() *UserSubscriptionUpdate {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetStripePriceID sets the "stripe_price_id" field.
func (_u *UserSubscriptionUpdate) SetStripePriceID(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStripePriceID(v)
	return _u
}

// SetNillableStripePriceID sets the "stripe_price_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStripePriceID(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStripePriceID(*v)
	}
	return _u
}

// ClearStripePriceID clears the value of the "stripe_price_id" field.
func (_u *UserSubscriptionUpdate) ClearStripePriceID() *UserSubscriptionUpdate {
	_u.mutation.ClearStripePriceID()
	return _u
}

// SetStripeEnvironment sets the "stripe_environment" field.
func (_u *UserSubscriptionUpdate) SetStripeEnvironment(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStripeEnvironment(v)
	return _u
}

// SetNillableStripeEnvironment sets the "stripe_environment" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStripeEnvironment(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStripeEnvironment(*v)
	}
	return _u
}

// SetStripeProviderInstanceID sets the "stripe_provider_instance_id" field.
func (_u *UserSubscriptionUpdate) SetStripeProviderInstanceID(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStripeProviderInstanceID(v)
	return _u
}

// SetNillableStripeProviderInstanceID sets the "stripe_provider_instance_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStripeProviderInstanceID(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStripeProviderInstanceID(*v)
	}
	return _u
}

// ClearStripeProviderInstanceID clears the value of the "stripe_provider_instance_id" field.
func (_u *UserSubscriptionUpdate) ClearStripeProviderInstanceID() *UserSubscriptionUpdate {
	_u.mutation.ClearStripeProviderInstanceID()
	return _u
}

// SetStripeStatus sets the "stripe_status" field.
func (_u *UserSubscriptionUpdate) SetStripeStatus(v string) *UserSubscriptionUpdate {
	_u.mutation.SetStripeStatus(v)
	return _u
}

// SetNillableStripeStatus sets the "stripe_status" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableStripeStatus(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetStripeStatus(*v)
	}
	return _u
}

// ClearStripeStatus clears the value of the "stripe_status" field.
func (_u *UserSubscriptionUpdate) ClearStripeStatus() *UserSubscriptionUpdate {
	_u.mutation.ClearStripeStatus()
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *UserSubscriptionUpdate) SetCurrentPeriodStart(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableCurrentPeriodStart(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *UserSubscriptionUpdate) ClearCurrentPeriodStart() *UserSubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *UserSubscriptionUpdate) SetCurrentPeriodEnd(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableCurrentPeriodEnd(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *UserSubscriptionUpdate) ClearCurrentPeriodEnd() *UserSubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetTrialStart sets the "trial_start" field.
func (_u *UserSubscriptionUpdate) SetTrialStart(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetTrialStart(v)
	return _u
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableTrialStart(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetTrialStart(*v)
	}
	return _u
}

// ClearTrialStart clears the value of the "trial_start" field.
func (_u *UserSubscriptionUpdate) ClearTrialStart() *UserSubscriptionUpdate {
	_u.mutation.ClearTrialStart()
	return _u
}

// SetTrialEnd sets the "trial_end" field.
func (_u *UserSubscriptionUpdate) SetTrialEnd(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetTrialEnd(v)
	return _u
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableTrialEnd(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetTrialEnd(*v)
	}
	return _u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (_u *UserSubscriptionUpdate) ClearTrialEnd() *UserSubscriptionUpdate {
	_u.mutation.ClearTrialEnd()
	return _u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_u *UserSubscriptionUpdate) SetCancelAtPeriodEnd(v bool) *UserSubscriptionUpdate {
	_u.mutation.SetCancelAtPeriodEnd(v)
	return _u
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableCancelAtPeriodEnd(v *bool) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetCancelAtPeriodEnd(*v)
	}
	return _u
}

// SetPastDueSince sets the "past_due_since" field.
func (_u *UserSubscriptionUpdate) SetPastDueSince(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetPastDueSince(v)
	return _u
}

// SetNillablePastDueSince sets the "past_due_since" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillablePastDueSince(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetPastDueSince(*v)
	}
	return _u
}

// ClearPastDueSince clears the value of the "past_due_since" field.
func (_u *UserSubscriptionUpdate) ClearPastDueSince() *UserSubscriptionUpdate {
	_u.mutation.ClearPastDueSince()
	return _u
}

// SetTrialUsed sets the "trial_used" field.
func (_u *UserSubscriptionUpdate) SetTrialUsed(v bool) *UserSubscriptionUpdate {
	_u.mutation.SetTrialUsed(v)
	return _u
}

// SetNillableTrialUsed sets the "trial_used" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableTrialUsed(v *bool) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetTrialUsed(*v)
	}
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserSubscriptionUpdate) SetDailyWindowStart(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableDailyWindowStart(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserSubscriptionUpdate) ClearDailyWindowStart() *UserSubscriptionUpdate {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserSubscriptionUpdate) SetWeeklyWindowStart(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableWeeklyWindowStart(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserSubscriptionUpdate) ClearWeeklyWindowStart() *UserSubscriptionUpdate {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserSubscriptionUpdate) SetMonthlyWindowStart(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableMonthlyWindowStart(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserSubscriptionUpdate) ClearMonthlyWindowStart() *UserSubscriptionUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserSubscriptionUpdate) SetDailyUsageUsd(v float64) *UserSubscriptionUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableDailyUsageUsd(v *float64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserSubscriptionUpdate) AddDailyUsageUsd(v float64) *UserSubscriptionUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserSubscriptionUpdate) SetWeeklyUsageUsd(v float64) *UserSubscriptionUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableWeeklyUsageUsd(v *float64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserSubscriptionUpdate) AddWeeklyUsageUsd(v float64) *UserSubscriptionUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserSubscriptionUpdate) SetMonthlyUsageUsd(v float64) *UserSubscriptionUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableMonthlyUsageUsd(v *float64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserSubscriptionUpdate) AddMonthlyUsageUsd(v float64) *UserSubscriptionUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserSubscriptionUpdate) SetAssignedBy(v int64) *UserSubscriptionUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableAssignedBy(v *int64) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserSubscriptionUpdate) ClearAssignedBy() *UserSubscriptionUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserSubscriptionUpdate) SetAssignedAt(v time.Time) *UserSubscriptionUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableAssignedAt(v *time.Time) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserSubscriptionUpdate) SetNotes(v string) *UserSubscriptionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableNotes(v *string) *UserSubscriptionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserSubscriptionUpdate) ClearNotes() *UserSubscriptionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserSubscriptionUpdate) SetUser(v *User) *UserSubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserSubscriptionUpdate) SetGroup(v *Group) *UserSubscriptionUpdate {
	return _u.SetGroupID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *UserSubscriptionUpdate) SetAssignedByUserID(id int64) *UserSubscriptionUpdate {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *UserSubscriptionUpdate) SetNillableAssignedByUserID(id *int64) *UserSubscriptionUpdate {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *UserSubscriptionUpdate) SetAssignedByUser(v *User) *UserSubscriptionUpdate {
	return _u.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *UserSubscriptionUpdate) AddUsageLogIDs(ids ...int64) *UserSubscriptionUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *UserSubscriptionUpdate) AddUsageLogs(v ...*UsageLog) *UserSubscriptionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (_u *UserSubscriptionUpdate) Mutation() *UserSubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserSubscriptionUpdate) ClearUser() *UserSubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserSubscriptionUpdate) ClearGroup() *UserSubscriptionUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *UserSubscriptionUpdate) ClearAssignedByUser() *UserSubscriptionUpdate {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *UserSubscriptionUpdate) ClearUsageLogs() *UserSubscriptionUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *UserSubscriptionUpdate) RemoveUsageLogIDs(ids ...int64) *UserSubscriptionUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *UserSubscriptionUpdate) RemoveUsageLogs(v ...*UsageLog) *UserSubscriptionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSubscriptionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscriptionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usersubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usersubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeCustomerID(); ok {
		if err := usersubscription.StripeCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_customer_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeSubscriptionID(); ok {
		if err := usersubscription.StripeSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_subscription_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripePriceID(); ok {
		if err := usersubscription.StripePriceIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_price_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_price_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeEnvironment(); ok {
		if err := usersubscription.StripeEnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "stripe_environment", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_environment": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeProviderInstanceID(); ok {
		if err := usersubscription.StripeProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeStatus(); ok {
		if err := usersubscription.StripeStatusValidator(v); err != nil {
			return &ValidationError{Name: "stripe_status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscription.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscription.group"`)
	}
	return nil
}

func (_u *UserSubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscription.Table, usersubscription.Columns, sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usersubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usersubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(usersubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(usersubscription.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(usersubscription.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(usersubscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(usersubscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.StripePriceID(); ok {
		_spec.SetField(usersubscription.FieldStripePriceID, field.TypeString, value)
	}
	if _u.mutation.StripePriceIDCleared() {
		_spec.ClearField(usersubscription.FieldStripePriceID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeEnvironment(); ok {
		_spec.SetField(usersubscription.FieldStripeEnvironment, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripeProviderInstanceID(); ok {
		_spec.SetField(usersubscription.FieldStripeProviderInstanceID, field.TypeString, value)
	}
	if _u.mutation.StripeProviderInstanceIDCleared() {
		_spec.ClearField(usersubscription.FieldStripeProviderInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeStatus(); ok {
		_spec.SetField(usersubscription.FieldStripeStatus, field.TypeString, value)
	}
	if _u.mutation.StripeStatusCleared() {
		_spec.ClearField(usersubscription.FieldStripeStatus, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(usersubscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(usersubscription.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(usersubscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(usersubscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialStart(); ok {
		_spec.SetField(usersubscription.FieldTrialStart, field.TypeTime, value)
	}
	if _u.mutation.TrialStartCleared() {
		_spec.ClearField(usersubscription.FieldTrialStart, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialEnd(); ok {
		_spec.SetField(usersubscription.FieldTrialEnd, field.TypeTime, value)
	}
	if _u.mutation.TrialEndCleared() {
		_spec.ClearField(usersubscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(usersubscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PastDueSince(); ok {
		_spec.SetField(usersubscription.FieldPastDueSince, field.TypeTime, value)
	}
	if _u.mutation.PastDueSinceCleared() {
		_spec.ClearField(usersubscription.FieldPastDueSince, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialUsed(); ok {
		_spec.SetField(usersubscription.FieldTrialUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usersubscription.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usersubscription.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usersubscription.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usersubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usersubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usersubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(usersubscription.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(usersubscription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(usersubscription.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.UserTable,
			Columns: []string{usersubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.UserTable,
			Columns: []string{usersubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.GroupTable,
			Columns: []string{usersubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.GroupTable,
			Columns: []string{usersubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.AssignedByUserTable,
			Columns: []string{usersubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.AssignedByUserTable,
			Columns: []string{usersubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSubscriptionUpdateOne is the builder for updating a single UserSubscription entity.
type UserSubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSubscriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscriptionUpdateOne) SetUpdatedAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserSubscriptionUpdateOne) SetDeletedAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableDeletedAt(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserSubscriptionUpdateOne) ClearDeletedAt() *UserSubscriptionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSubscriptionUpdateOne) SetUserID(v int64) *UserSubscriptionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableUserID(v *int64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserSubscriptionUpdateOne) SetGroupID(v int64) *UserSubscriptionUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableGroupID(v *int64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserSubscriptionUpdateOne) SetStartsAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStartsAt(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserSubscriptionUpdateOne) SetExpiresAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableExpiresAt(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscriptionUpdateOne) SetStatus(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStatus(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStripeCustomerID sets the "stripe_customer_id" field.
func (_u *UserSubscriptionUpdateOne) SetStripeCustomerID(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStripeCustomerID(v)
	return _u
}

// SetNillableStripeCustomerID sets the "stripe_customer_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStripeCustomerID(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeCustomerID(*v)
	}
	return _u
}

// ClearStripeCustomerID clears the value of the "stripe_customer_id" field.
func (_u *UserSubscriptionUpdateOne) ClearStripeCustomerID() *UserSubscriptionUpdateOne {
	_u.mutation.ClearStripeCustomerID()
	return _u
}

// SetStripeSubscriptionID sets the "stripe_subscription_id" field.
func (_u *UserSubscriptionUpdateOne) SetStripeSubscriptionID(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStripeSubscriptionID(v)
	return _u
}

// SetNillableStripeSubscriptionID sets the "stripe_subscription_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStripeSubscriptionID(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeSubscriptionID(*v)
	}
	return _u
}

// ClearStripeSubscriptionID clears the value of the "stripe_subscription_id" field.
func (_u *UserSubscriptionUpdateOne) ClearStripeSubscriptionID() *UserSubscriptionUpdateOne {
	_u.mutation.ClearStripeSubscriptionID()
	return _u
}

// SetStripePriceID sets the "stripe_price_id" field.
func (_u *UserSubscriptionUpdateOne) SetStripePriceID(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStripePriceID(v)
	return _u
}

// SetNillableStripePriceID sets the "stripe_price_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStripePriceID(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStripePriceID(*v)
	}
	return _u
}

// ClearStripePriceID clears the value of the "stripe_price_id" field.
func (_u *UserSubscriptionUpdateOne) ClearStripePriceID() *UserSubscriptionUpdateOne {
	_u.mutation.ClearStripePriceID()
	return _u
}

// SetStripeEnvironment sets the "stripe_environment" field.
func (_u *UserSubscriptionUpdateOne) SetStripeEnvironment(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStripeEnvironment(v)
	return _u
}

// SetNillableStripeEnvironment sets the "stripe_environment" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStripeEnvironment(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeEnvironment(*v)
	}
	return _u
}

// SetStripeProviderInstanceID sets the "stripe_provider_instance_id" field.
func (_u *UserSubscriptionUpdateOne) SetStripeProviderInstanceID(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStripeProviderInstanceID(v)
	return _u
}

// SetNillableStripeProviderInstanceID sets the "stripe_provider_instance_id" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStripeProviderInstanceID(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeProviderInstanceID(*v)
	}
	return _u
}

// ClearStripeProviderInstanceID clears the value of the "stripe_provider_instance_id" field.
func (_u *UserSubscriptionUpdateOne) ClearStripeProviderInstanceID() *UserSubscriptionUpdateOne {
	_u.mutation.ClearStripeProviderInstanceID()
	return _u
}

// SetStripeStatus sets the "stripe_status" field.
func (_u *UserSubscriptionUpdateOne) SetStripeStatus(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetStripeStatus(v)
	return _u
}

// SetNillableStripeStatus sets the "stripe_status" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableStripeStatus(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetStripeStatus(*v)
	}
	return _u
}

// ClearStripeStatus clears the value of the "stripe_status" field.
func (_u *UserSubscriptionUpdateOne) ClearStripeStatus() *UserSubscriptionUpdateOne {
	_u.mutation.ClearStripeStatus()
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *UserSubscriptionUpdateOne) SetCurrentPeriodStart(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableCurrentPeriodStart(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *UserSubscriptionUpdateOne) ClearCurrentPeriodStart() *UserSubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *UserSubscriptionUpdateOne) SetCurrentPeriodEnd(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableCurrentPeriodEnd(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *UserSubscriptionUpdateOne) ClearCurrentPeriodEnd() *UserSubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetTrialStart sets the "trial_start" field.
func (_u *UserSubscriptionUpdateOne) SetTrialStart(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetTrialStart(v)
	return _u
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableTrialStart(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetTrialStart(*v)
	}
	return _u
}

// ClearTrialStart clears the value of the "trial_start" field.
func (_u *UserSubscriptionUpdateOne) ClearTrialStart() *UserSubscriptionUpdateOne {
	_u.mutation.ClearTrialStart()
	return _u
}

// SetTrialEnd sets the "trial_end" field.
func (_u *UserSubscriptionUpdateOne) SetTrialEnd(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetTrialEnd(v)
	return _u
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableTrialEnd(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetTrialEnd(*v)
	}
	return _u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (_u *UserSubscriptionUpdateOne) ClearTrialEnd() *UserSubscriptionUpdateOne {
	_u.mutation.ClearTrialEnd()
	return _u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_u *UserSubscriptionUpdateOne) SetCancelAtPeriodEnd(v bool) *UserSubscriptionUpdateOne {
	_u.mutation.SetCancelAtPeriodEnd(v)
	return _u
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableCancelAtPeriodEnd(v *bool) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetCancelAtPeriodEnd(*v)
	}
	return _u
}

// SetPastDueSince sets the "past_due_since" field.
func (_u *UserSubscriptionUpdateOne) SetPastDueSince(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetPastDueSince(v)
	return _u
}

// SetNillablePastDueSince sets the "past_due_since" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillablePastDueSince(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetPastDueSince(*v)
	}
	return _u
}

// ClearPastDueSince clears the value of the "past_due_since" field.
func (_u *UserSubscriptionUpdateOne) ClearPastDueSince() *UserSubscriptionUpdateOne {
	_u.mutation.ClearPastDueSince()
	return _u
}

// SetTrialUsed sets the "trial_used" field.
func (_u *UserSubscriptionUpdateOne) SetTrialUsed(v bool) *UserSubscriptionUpdateOne {
	_u.mutation.SetTrialUsed(v)
	return _u
}

// SetNillableTrialUsed sets the "trial_used" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableTrialUsed(v *bool) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetTrialUsed(*v)
	}
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserSubscriptionUpdateOne) SetDailyWindowStart(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableDailyWindowStart(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserSubscriptionUpdateOne) ClearDailyWindowStart() *UserSubscriptionUpdateOne {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserSubscriptionUpdateOne) SetWeeklyWindowStart(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableWeeklyWindowStart(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserSubscriptionUpdateOne) ClearWeeklyWindowStart() *UserSubscriptionUpdateOne {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserSubscriptionUpdateOne) SetMonthlyWindowStart(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserSubscriptionUpdateOne) ClearMonthlyWindowStart() *UserSubscriptionUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserSubscriptionUpdateOne) SetDailyUsageUsd(v float64) *UserSubscriptionUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableDailyUsageUsd(v *float64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserSubscriptionUpdateOne) AddDailyUsageUsd(v float64) *UserSubscriptionUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserSubscriptionUpdateOne) SetWeeklyUsageUsd(v float64) *UserSubscriptionUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserSubscriptionUpdateOne) AddWeeklyUsageUsd(v float64) *UserSubscriptionUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserSubscriptionUpdateOne) SetMonthlyUsageUsd(v float64) *UserSubscriptionUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserSubscriptionUpdateOne) AddMonthlyUsageUsd(v float64) *UserSubscriptionUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserSubscriptionUpdateOne) SetAssignedBy(v int64) *UserSubscriptionUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableAssignedBy(v *int64) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserSubscriptionUpdateOne) ClearAssignedBy() *UserSubscriptionUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserSubscriptionUpdateOne) SetAssignedAt(v time.Time) *UserSubscriptionUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableAssignedAt(v *time.Time) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserSubscriptionUpdateOne) SetNotes(v string) *UserSubscriptionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableNotes(v *string) *UserSubscriptionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserSubscriptionUpdateOne) ClearNotes() *UserSubscriptionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserSubscriptionUpdateOne) SetUser(v *User) *UserSubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserSubscriptionUpdateOne) SetGroup(v *Group) *UserSubscriptionUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID.
func (_u *UserSubscriptionUpdateOne) SetAssignedByUserID(id int64) *UserSubscriptionUpdateOne {
	_u.mutation.SetAssignedByUserID(id)
	return _u
}

// SetNillableAssignedByUserID sets the "assigned_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *UserSubscriptionUpdateOne) SetNillableAssignedByUserID(id *int64) *UserSubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetAssignedByUserID(*id)
	}
	return _u
}

// SetAssignedByUser sets the "assigned_by_user" edge to the User entity.
func (_u *UserSubscriptionUpdateOne) SetAssignedByUser(v *User) *UserSubscriptionUpdateOne {
	return _u.SetAssignedByUserID(v.ID)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *UserSubscriptionUpdateOne) AddUsageLogIDs(ids ...int64) *UserSubscriptionUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *UserSubscriptionUpdateOne) AddUsageLogs(v ...*UsageLog) *UserSubscriptionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the UserSubscriptionMutation object of the builder.
func (_u *UserSubscriptionUpdateOne) Mutation() *UserSubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserSubscriptionUpdateOne) ClearUser() *UserSubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserSubscriptionUpdateOne) ClearGroup() *UserSubscriptionUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAssignedByUser clears the "assigned_by_user" edge to the User entity.
func (_u *UserSubscriptionUpdateOne) ClearAssignedByUser() *UserSubscriptionUpdateOne {
	_u.mutation.ClearAssignedByUser()
	return _u
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *UserSubscriptionUpdateOne) ClearUsageLogs() *UserSubscriptionUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *UserSubscriptionUpdateOne) RemoveUsageLogIDs(ids ...int64) *UserSubscriptionUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *UserSubscriptionUpdateOne) RemoveUsageLogs(v ...*UsageLog) *UserSubscriptionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the UserSubscriptionUpdate builder.
func (_u *UserSubscriptionUpdateOne) Where(ps ...predicate.UserSubscription) *UserSubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSubscriptionUpdateOne) Select(field string, fields ...string) *UserSubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSubscription entity.
func (_u *UserSubscriptionUpdateOne) Save(ctx context.Context) (*UserSubscription, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionUpdateOne) SaveX(ctx context.Context) *UserSubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscriptionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usersubscription.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usersubscription.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usersubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := usersubscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeCustomerID(); ok {
		if err := usersubscription.StripeCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_customer_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeSubscriptionID(); ok {
		if err := usersubscription.StripeSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_subscription_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripePriceID(); ok {
		if err := usersubscription.StripePriceIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_price_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_price_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeEnvironment(); ok {
		if err := usersubscription.StripeEnvironmentValidator(v); err != nil {
			return &ValidationError{Name: "stripe_environment", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_environment": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeProviderInstanceID(); ok {
		if err := usersubscription.StripeProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeStatus(); ok {
		if err := usersubscription.StripeStatusValidator(v); err != nil {
			return &ValidationError{Name: "stripe_status", err: fmt.Errorf(`ent: validator failed for field "UserSubscription.stripe_status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscription.user"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscription.group"`)
	}
	return nil
}

func (_u *UserSubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *UserSubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscription.Table, usersubscription.Columns, sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscription.FieldID)
		for _, f := range fields {
			if !usersubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usersubscription.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usersubscription.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(usersubscription.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscription.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripeCustomerID(); ok {
		_spec.SetField(usersubscription.FieldStripeCustomerID, field.TypeString, value)
	}
	if _u.mutation.StripeCustomerIDCleared() {
		_spec.ClearField(usersubscription.FieldStripeCustomerID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeSubscriptionID(); ok {
		_spec.SetField(usersubscription.FieldStripeSubscriptionID, field.TypeString, value)
	}
	if _u.mutation.StripeSubscriptionIDCleared() {
		_spec.ClearField(usersubscription.FieldStripeSubscriptionID, field.TypeString)
	}
	if value, ok := _u.mutation.StripePriceID(); ok {
		_spec.SetField(usersubscription.FieldStripePriceID, field.TypeString, value)
	}
	if _u.mutation.StripePriceIDCleared() {
		_spec.ClearField(usersubscription.FieldStripePriceID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeEnvironment(); ok {
		_spec.SetField(usersubscription.FieldStripeEnvironment, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripeProviderInstanceID(); ok {
		_spec.SetField(usersubscription.FieldStripeProviderInstanceID, field.TypeString, value)
	}
	if _u.mutation.StripeProviderInstanceIDCleared() {
		_spec.ClearField(usersubscription.FieldStripeProviderInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.StripeStatus(); ok {
		_spec.SetField(usersubscription.FieldStripeStatus, field.TypeString, value)
	}
	if _u.mutation.StripeStatusCleared() {
		_spec.ClearField(usersubscription.FieldStripeStatus, field.TypeString)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(usersubscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(usersubscription.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(usersubscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(usersubscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialStart(); ok {
		_spec.SetField(usersubscription.FieldTrialStart, field.TypeTime, value)
	}
	if _u.mutation.TrialStartCleared() {
		_spec.ClearField(usersubscription.FieldTrialStart, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialEnd(); ok {
		_spec.SetField(usersubscription.FieldTrialEnd, field.TypeTime, value)
	}
	if _u.mutation.TrialEndCleared() {
		_spec.ClearField(usersubscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(usersubscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PastDueSince(); ok {
		_spec.SetField(usersubscription.FieldPastDueSince, field.TypeTime, value)
	}
	if _u.mutation.PastDueSinceCleared() {
		_spec.ClearField(usersubscription.FieldPastDueSince, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialUsed(); ok {
		_spec.SetField(usersubscription.FieldTrialUsed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usersubscription.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usersubscription.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usersubscription.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usersubscription.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usersubscription.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usersubscription.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usersubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usersubscription.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(usersubscription.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(usersubscription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(usersubscription.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.UserTable,
			Columns: []string{usersubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.UserTable,
			Columns: []string{usersubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.GroupTable,
			Columns: []string{usersubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.GroupTable,
			Columns: []string{usersubscription.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.AssignedByUserTable,
			Columns: []string{usersubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscription.AssignedByUserTable,
			Columns: []string{usersubscription.AssignedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscription.UsageLogsTable,
			Columns: []string{usersubscription.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserSubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
